FROM pptx2h5p/pyinstaller
LABEL author="Martin Lehmann (https://github.com/MM-Lehmann)"

COPY requirements.txt .
RUN wine pip install --no-warn-script-location --no-cache -r requirements.txt

COPY docker/entrypoint.sh /opt/
ENTRYPOINT ["/opt/entrypoint.sh"]